services:
  php-8.2:
    image: phpstorm/php-cli:8.2-xdebug3.2
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "apt-get update &&
               apt-get install -y libsqlite3-dev &&
               apt-get clean &&
               rm -rf /var/lib/apt/lists/* &&
               tail -f /dev/null"

  php-8.3:
    image: oanhnn/php:8.3-cli
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "apt-get update &&
               apt-get install -y libsqlite3-dev &&
               apt-get clean &&
               rm -rf /var/lib/apt/lists/* &&
               tail -f /dev/null"

  php-8.4:
    image: oanhnn/php:8.4-cli
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "apt-get update &&
               apt-get install -y libsqlite3-dev &&
               apt-get clean &&
               rm -rf /var/lib/apt/lists/* &&
               tail -f /dev/null"
